// Generated by CoffeeScript 1.11.1
Phacker.Game.Socle = (function() {
  function Socle(gm) {
    this._fle_ = 'SOCLe';
    this.gm = gm;
    this.pfm = this.gm.add.group();
    this.pfm.enableBody = true;
    this.key_down = false;
    this.gus = {};
  }

  Socle.prototype.set_group = function() {
    this.draw_sky();
    this.draw_btns();
    return this.pfm;
  };

  Socle.prototype.draw_sky = function() {
    this.sky = this.pfm.create(0, 48, 'sky');
    this.gm.world.sendToBack(this.sky);
    return this.sky.fixedToCamera = true;
  };

  Socle.prototype.draw_btns = function() {
    var x, y;
    x = this.gm.jmp_btn.x;
    y = this.gm.jmp_btn.y;
    this.jmp_btn = this.gm.add.button(x, y, 'jmp_btn', this.jump, this, 1, 1, 0);
    return this.jmp_btn.fixedToCamera = true;
  };

  Socle.prototype.bind = function(ply) {
    return this.gus = ply;
  };

  Socle.prototype.jump = function() {
    var ref;
    if ((4 > (ref = this.gus.body.velocity.y) && ref > -1)) {
      this.gus.body.velocity.y = this.gm.gus.vy;
      return this.gus.body.drag.x = this.gm.gus.drag;
    }
  };

  return Socle;

})();
